#######################################################
# Nano with docker-compose
#
# Please edit only if you know what you are doing.
# Please use spaces when editing.
# If you need any help, join our discord server at http://discord.nanobot.pw


version: '3'
services:
  nano:
    # ##########
    # IMPORTANT: This should only be used for building an image from source or for testing!
    # tl;dr: Don't uncomment this if you don't know what you are doing.
    # ##########
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: defaltsimon/nano:latest

    ######
    # Both nano and redis databases share the same directory - /data
    # This mounts the data directory (in your current directory) to data/ inside the container
    # so your configuration is saved and can be modified outside of the container
    ######
    volumes:
      - ./data:/data

    # This makes sure redis-data and redis-cache are started first.
    depends_on:
      - redis_data
      - redis_cache

  #########################
  # REDIS DATA instance
  #########################
  redis_data:
    image: redis:6.0

    # Mounts all database files into your data/ directory
    volumes:
      - ./data:/data
    command: "redis-server /data/redis.conf"

  #########################
  # REDIS CACHE instance
  #########################
  redis_cache:
    image: redis:6.0

    # Mounts all database files into your data/ directory
    volumes:
      - ./data:/data
    command: "redis-server /data/redisCache.conf"
